joint_limits:
  robot_j2s7s300_joint_1:
    has_velocity_limits: true
    max_velocity: 0.62831853
    has_acceleration_limits: true
    max_acceleration: 2.5132741
  robot_j2s7s300_joint_2:
    has_velocity_limits: true
    max_velocity: 0.62831853
    has_acceleration_limits: true
    max_acceleration: 2.5132741
  robot_j2s7s300_joint_3:
    has_velocity_limits: true
    max_velocity: 0.62831853
    has_acceleration_limits: true
    max_acceleration: 2.5132741
  robot_j2s7s300_joint_4:
    has_velocity_limits: true
    max_velocity: 0.62831853
    has_acceleration_limits: true
    max_acceleration: 2.5132741
  robot_j2s7s300_joint_5:
    has_velocity_limits: true
    max_velocity: 0.83775804
    has_acceleration_limits: true
    max_acceleration: 3.3510321
  robot_j2s7s300_joint_6:
    has_velocity_limits: true
    max_velocity: 0.83775804
    has_acceleration_limits: true
    max_acceleration: 3.3510321
  robot_j2s7s300_joint_7:
    has_velocity_limits: true
    max_velocity: 0.83775804
    has_acceleration_limits: true
    max_acceleration: 3.3510321
  robot_j2s7s300_joint_finger_1:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 2.5
  robot_j2s7s300_joint_finger_2:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 2.5
  robot_j2s7s300_joint_finger_3:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 2.5
