arm:
  # kinematics_solver: kdl_kinematics_plugin/KdsaDLKinematicsPlugin
  kinematics_solver: cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin
  # kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin
  kinematics_solver_search_resolution: 0.002
  kinematics_solver_timeout: 0.01
  kinematics_solver_attempts: 3
  max_cache_size: 100000
