<?xml version="1.0"?>
<!-- Macro for creation of Summit XL (base and wheels) -->
<robot xmlns:xacro="http://wiki.ros.org/xacro">

  <!--                   -->
  <!-- Imported elements -->
  <!--                   -->
  <!-- Import Summit XL base -->
  <xacro:include filename="$(find lunalab_summit_xl_gen_description)/urdf/summit_xl/summit_xl_base.xacro"/>

  <!-- Import Summit XL wheels (rubber) -->
  <xacro:include filename="$(find lunalab_summit_xl_gen_description)/urdf/summit_xl/rubber_wheel.xacro"/>

  <!-- Gazebo plugins -->
  <xacro:include filename="$(find lunalab_summit_xl_gen_description)/urdf/summit_xl/summit_xl.gazebo"/>

  <!--            -->
  <!-- Properties -->
  <!--            -->
  <!-- Wheel offset (from base_link to the center of the wheel) -->
  <xacro:property name="wheel_offset_x" value="0.229"/>
  <xacro:property name="wheel_offset_y" value="0.235"/>
  <xacro:property name="wheel_offset_z" value="0.0"/>


  <!--       -->
  <!-- Macro -->
  <!--       -->
  <!-- prefix                        - Prefix for all entities -->
  <!-- add_base_footprint            - Flag that enables base footprint link -->
  <!-- high_quality_mesh             - Flag to select the high or low quality model -->
  <xacro:macro name="summit_xl" params="
    prefix:=summit_xl_
    add_base_footprint:=true
    high_quality_mesh:=true
    gazebo_diff_drive:=true
  ">
    <!-- Radius of wheels based on the utilised wheels (only default rubber wheels are currently supported) -->
    <xacro:property name="wheel_radius" value="${rubber_wheel_radius}"/>

    <!-- Summit XL base -->
    <xacro:summit_xl_base prefix="${prefix}" add_base_footprint="${add_base_footprint}" high_quality_mesh="${high_quality_mesh}"/>

    <!-- Wheels (rubber) -->
    <xacro:rubber_wheel prefix="${prefix}front_left_" parent="${prefix}base_link" left_wheel="true" high_quality_mesh="${high_quality_mesh}">
      <origin xyz="${wheel_offset_x} ${wheel_offset_y} ${wheel_offset_z}" rpy="0 0 0"/>
    </xacro:rubber_wheel>
    <xacro:rubber_wheel prefix="${prefix}back_left_" parent="${prefix}base_link" left_wheel="true" high_quality_mesh="${high_quality_mesh}">
      <origin xyz="-${wheel_offset_x} ${wheel_offset_y} ${wheel_offset_z}" rpy="0 0 0"/>
    </xacro:rubber_wheel>
    <xacro:rubber_wheel prefix="${prefix}front_right_" parent="${prefix}base_link" left_wheel="false" high_quality_mesh="${high_quality_mesh}">
      <origin xyz="${wheel_offset_x} -${wheel_offset_y} ${wheel_offset_z}" rpy="0 0 0"/>
    </xacro:rubber_wheel>
    <xacro:rubber_wheel prefix="${prefix}back_right_" parent="${prefix}base_link" left_wheel="false" high_quality_mesh="${high_quality_mesh}">
      <origin xyz="-${wheel_offset_x} -${wheel_offset_y} ${wheel_offset_z}" rpy="0 0 0"/>
    </xacro:rubber_wheel>

    <!-- Gazebo - Differential drive -->
    <xacro:if value="${gazebo_diff_drive}">
      <xacro:gazebo_diff_drive prefix="${prefix}" wheel_separation="${2*wheel_offset_y}" wheel_radius="${wheel_radius}"/>
    </xacro:if>
  </xacro:macro>

</robot>
