initial_joint_positions:
  j2s7s300:
    joint_1: 0.0
    joint_2: 3.490658504
    joint_3: 0.0
    joint_4: 5.235987756
    joint_5: 0.0
    joint_6: 1.745329252
    joint_7: 0.0
  kinova_3fingers:
    joint_1: 0.2
    joint_2: 0.2
    joint_3: 0.2
